# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'darkSky' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for darkSky
  pod 'PinLayout'
  pod 'Alamofire', '~> 5.0.0-beta.3'
  pod 'SwiftLint', '~> 0.27'
  pod 'ESPullToRefresh'

end
